# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Lake
email: me@mgtlake.com
description: > # this means to ignore newlines until "baseurl:"
   TEST
   A rambling blog and mediocre portfolio by Matthew Lake, an unremarkable undergrad software engineer.
   Everything I write is my own opinion, of course. If you like reading what I've written, keeping doing so, and if you don't, why are you still reading this?
   See <a href='/about'>about me</a> for less self-deprecation.
   <br> 
   This page best viewed with <a href='http://lynx.browser.org/'>Lynx</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mgtlake.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  matthew-lake

# Build settings
markdown: kramdown
#highlighter: pygments
